base_url = "https://secmetrics.no"

compile_sass = false

build_search_index = true

[markdown]
highlight_code = false

[extra]
company_name = "Secmetrics AS"
email = "hello@secmetrics.no"
phone = "+47-88888888"
address = "Hunnsvegen 3, 2817 Gjøvik, Norway"

hero_title = "Secure Your Digital Future"
hero_subtitle = "Protect your digital assets with AI-powered security solutions."

ganalytics = "G-CSEM88E4KP"

generate_sitemap = true
